#!/usr/bin/env php
<?php

date_default_timezone_set('Etc/GMT+0');

use App\Console\Input;
use App\MainController;

require_once "./vendor/autoload.php";

$fast = new MainController(
    new Input()
);
$fast->run();
